spring:
  #  配置数据源
  datasource:
    username: root
    password: 8888
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://localhost:3306/sims_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      #配置从连接池获取连接时，是否检查连接有效性，true每次都检查；false不检查。做了这个配置会降低性能。
      testOnBorrow: false
      #配置向连接池归还连接时，是否检查连接有效性，true每次都检查；false不检查。做了这个配置会降低性能。
      testOnReturn: false
      #打开PsCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      #合并多个DruidDatasource的监控数据
      useGlobalDataSourceStat: true
      #通过connectProperties属性来打开mergesql功能罗慢sQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;

  cloud:
    alicloud:
      bucket-name: sims-web-jsy #上传空间bucket
      access-key: LTAI4GEtRcJPLmafNZJJAH3G #你的key
      secret-key: 7ZcF61t63i7IQB7Hv6ydevkbtShJ9Q #你的秘钥
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com #上传端点



server:
  port: 8088

mybatis:
  configuration:
#    mybatis的日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #  mapper文件
  mapper-locations: classpath:mapper/*.xml
  #  配置类型别名，避免每次冗余的全限定名
  type-aliases-package: com.jsy.simsserver.pojo


# 指定log4j2作为日志记录
logging:
  level:
    #这个指定你的dao层，也就是mapper文件的所在包
    com/jsy/simsserver/mapper: DEBUG